s# Spring Boot ?????? ??
spring.application.name=nae-vigator-server

# MySQL ?????? ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/nae_vigator_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA(Java Persistence API) ??
# ? ??? Entity? ?? DB ???? ???? ???? ??????.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true